//
//  BackendArtwork.swift
//  Muse Lens
//
//  Backend artwork data model for API communication
//

import Foundation

/// Backend artwork model matching database schema
struct BackendArtwork: Codable {
    let id: String?
    let combinedHash: String
    let normalizedTitle: String
    let normalizedArtist: String
    let title: String
    let titleEn: String?
    let artist: String
    let artistEn: String?
    let year: String?
    let style: String?
    let medium: String?
    let museum: String?
    let imageUrl: String?
    let sources: [String]
    let narration: String
    let narrationEn: String?
    let summary: String
    let confidence: Double
    let recognized: Bool
    let viewCount: Int?
    let lastViewedAt: Date?
    let createdAt: Date?
    let updatedAt: Date?
    
    enum CodingKeys: String, CodingKey {
        case id
        case combinedHash = "combined_hash"
        case normalizedTitle = "normalized_title"
        case normalizedArtist = "normalized_artist"
        case title
        case titleEn = "title_en"
        case artist
        case artistEn = "artist_en"
        case year
        case style
        case medium
        case museum
        case imageUrl = "image_url"
        case sources
        case narration
        case narrationEn = "narration_en"
        case summary
        case confidence
        case recognized
        case viewCount = "view_count"
        case lastViewedAt = "last_viewed_at"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
    
    /// Convert to NarrationResponse
    /// Note: artistIntroduction should be fetched separately from artists table
    func toNarrationResponse(artistIntroduction: String? = nil) -> NarrationResponse {
        return NarrationResponse(
            title: title,
            artist: artist,
            year: year,
            style: style,
            summary: summary,
            narration: narration,
            artistIntroduction: artistIntroduction,
            sources: sources,
            confidence: confidence
        )
    }
    
    /// Convert to ArtworkInfo
    func toArtworkInfo() -> ArtworkInfo {
        return ArtworkInfo(
            title: title,
            artist: artist,
            year: year,
            style: style,
            medium: medium,
            museum: museum,
            sources: sources,
            imageURL: imageUrl,
            recognized: recognized
        )
    }
    
    /// Create from NarrationResponse and identifier
    /// 
    /// CRITICAL: imageUrl should ONLY be from museum API (reference image), NEVER user's photo
    /// - imageUrl: Reference image from museum collection API (e.g., Met Museum, Art Institute)
    /// - User's personal photos are NEVER stored in backend
    /// - User's photos are only stored locally in history (HistoryItem.userPhotoData)
    /// - When displaying, PlaybackView always prioritizes userImage over artworkInfo.imageURL
    static func from(
        narrationResponse: NarrationResponse,
        identifier: ArtworkIdentifier,
        artworkInfo: ArtworkInfo? = nil
    ) -> BackendArtwork {
        // Only use imageURL from museum API (verifiedInfo), NEVER from user's photo
        // imageURL should be a reference image from museum collection API
        // User's personal photos are stored separately in local history, NOT in backend
        let referenceImageURL = artworkInfo?.imageURL // This should be from museum API only
        
        // Validate that imageURL is from a museum API, not a user photo
        // Museum API URLs typically contain museum domain names
        let isMuseumImageURL = referenceImageURL?.contains("metmuseum.org") == true ||
                               referenceImageURL?.contains("artic.edu") == true ||
                               referenceImageURL?.contains("wikimedia.org") == true ||
                               referenceImageURL?.contains("wikipedia.org") == true
        
        // Only use imageURL if it's from a museum API
        // If it's not a museum URL, set to nil to avoid storing user photos
        let safeImageURL = (isMuseumImageURL || referenceImageURL == nil) ? referenceImageURL : nil
        
        if let url = referenceImageURL, !isMuseumImageURL {
            print("⚠️ Warning: imageURL does not appear to be from museum API: \(url)")
            print("⚠️ Skipping imageURL to avoid storing user photos in backend")
        }
        
        // Ensure title is cleaned (no 《》 characters) for storage
        let cleanedTitle = ArtworkIdentifier.cleanTitle(narrationResponse.title)
        
        return BackendArtwork(
            id: nil, // Will be generated by backend
            combinedHash: identifier.combinedHash,
            normalizedTitle: identifier.normalizedTitle,
            normalizedArtist: identifier.normalizedArtist,
            title: cleanedTitle, // Store cleaned title (no 《》)
            titleEn: nil,
            artist: narrationResponse.artist,
            artistEn: nil,
            year: narrationResponse.year,
            style: narrationResponse.style,
            medium: artworkInfo?.medium,
            museum: artworkInfo?.museum,
            imageUrl: safeImageURL, // Only museum API reference image, NEVER user photo
            sources: narrationResponse.sources,
            narration: narrationResponse.narration,
            narrationEn: nil,
            summary: narrationResponse.summary,
            confidence: narrationResponse.confidence,
            recognized: narrationResponse.confidenceLevel == .high,
            viewCount: 1,
            lastViewedAt: Date(),
            createdAt: nil,
            updatedAt: nil
        )
    }
}

/// Backend artist model
struct BackendArtist: Codable {
    let id: String?
    let name: String
    let nameEn: String?
    let normalizedName: String
    let artistIntroduction: String?
    let artworksCount: Int?
    let createdAt: Date?
    let updatedAt: Date?
    
    enum CodingKeys: String, CodingKey {
        case id
        case name
        case nameEn = "name_en"
        case normalizedName = "normalized_name"
        case artistIntroduction = "artist_introduction"
        case artworksCount = "artworks_count"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

/// Backend API errors
enum BackendAPIError: Error {
    case requestFailed
    case saveFailed
    case notFound
    case invalidResponse
    case networkError
    case unauthorized
}

extension BackendAPIError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .requestFailed:
            return "Backend API request failed"
        case .saveFailed:
            return "Failed to save artwork to backend"
        case .notFound:
            return "Artwork not found in backend"
        case .invalidResponse:
            return "Invalid response from backend"
        case .networkError:
            return "Network error occurred"
        case .unauthorized:
            return "Unauthorized access to backend API"
        }
    }
}

